name: Pylint-Pytest

on:
  push:
    paths:
    - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Test with pytest
      run: |
        pytest
